### ISSUE TITLE
NAIF kernels required

### ISSUE THREAD

**Issue by migueldvb** [mkelley/mskpy#25]
The `_setup_spice` function in `ephem.core` loads some SPICE kernels. Are these kernels available from JPL Horizons?

```
    load_kernel("naif.tls")                                                              
    load_kernel("pck.tpc")                                                               
    load_kernel("planets.bsp")                                                           
    try:                                                                                 
        load_kernel("naif-names.txt")                                                    
```

Miguel

**Comment by mkelley** [comment]
Hi Miguel,

Not quite.  Those kernels are available at http://naif.jpl.nasa.gov/pub/naif/generic_kernels/ .  I'll edit the README to make this clear.  Also see the documentation for mskpy.ephem (About kernels).

- msk

**Comment by migueldvb** [comment]
Thank you! that is very helpful.
