### ISSUE TITLE
L2 point ephemeris

### ISSUE THREAD

**Issue by lursias** [mkelley/mskpy#34]
Hey,

I write to you in order to ask for some help or advice for a problem I have related to the subject. I'm a master student and I am trying to get the L2 ephemeris for the file you indicate in the README file, with the following syntax for my master's project:

from jplephem.spk import SPK
kernel = SPK.open('L2.bsp')
position = kernel[3,392].compute(2457061.5)

but I'm getting an exception: "Only SPK data types 2 and 3 are supported". 

Do you have any solution for this issue?

Sorry for bothering you and good work man.

**Comment by mkelley** [comment]
It can be done with the NAIF SPICE toolkit.  spiceypy provides python bindings.  After downloading the L2, planets, and leap seconds kernels (link in my README), the following might work for you:
```
spiceypy.furnsh('L2.bsp')
spiceypy.furnsh('de430.bsp')
spiceypy.furnsh('naif0011.tls')
et = spiceypy.str2et('2457061.5 JD')  # convert Julian date to ephemeris time
state, lt = spiceypy.spkezr('392', et, 'J2000', 'NONE', '10')
>>> print(state)
[-1.11935017e+08  9.02874343e+07  3.91412140e+07 -2.03562646e+01
 -2.08375916e+01 -9.03331976e+00]
```
Note that for the ephemeris time calculation, you may need to be careful with the conversion between time scales (e.g., UTC, TDB, etc.).

Documentation for the NAIF SPICE toolkit is at https://naif.jpl.nasa.gov/naif/documentation.html and spiceypy is at https://github.com/AndrewAnnex/SpiceyPy .  The "most used" page is a handy reference: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/info/mostused.html

**Comment by lursias** [comment]
Thank you! That helped me a lot. I managed to transform my old syntax to spice toolkit and got everything right. I dont really understand movement of L2 yet, but I suppose it's due to the coordinate system I'm using.

Thank you!

**Comment by mkelley** [comment]
No problem.
